services:
  db:
    image: postgres:15
    container_name: dss-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dsdojo_db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
      - TZ=Asia/Tokyo
    volumes:
      - type: bind
        source: ./docker/db/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./docker/db/data
        target: /tmp/data